### ISSUE TITLE
canto endpoint in cosmoshub load balancer

### ISSUE THREAD

**Issue by alagiz** [Stakely/web3-load-balancer-configuration#17]
hey guys, appreciate great load balancing service you provide.

one of the cosmoshub load balancer endpoints is pointing at canto instead of cosmoshub for several days already (https://rpc-cosmos.kewrnode.com/abci_info?)
https://github.com/Stakely/web3-load-balancer-configuration/blob/main/cosmoshub/rpc.json#L239
https://github.com/Stakely/web3-load-balancer-configuration/blob/main/cosmoshub/lcd.json#L217

don't know your exact strategy on adding/removing endpoints, it seems to be automated now, so i didn't make a pull request, will leave it up to you

**Comment by iicc1** [comment]
Hi alagiz, thanks for your words and the heads up!
We have removed that endpoint in https://github.com/Stakely/web3-load-balancer-configuration/pull/18.
We will implement a mechanism to remove wrongly configured nodes. This issue hasn't happened previously because we now automatically add new endpoints from the Cosmos Chain Registry and it seems it is not well maintained enough.
